### PR TITLE
Russian language full translation

### PR DESCRIPTION
**Pull request by insspb**

### CODE REVIEW

**Comment by samuelet** [comment]
Thanks insspb for patch but it's better to send translation using http://translate.dokuwiki.org/.
In this way, patches are sent to me by the transalte github user after they are verified by dokuwiki community.

**Comment by insspb** [comment]
It is impossible to do good translation on Russian without checking where is translated words used. Anyway it is you choice.

**Comment by Klap-in** [comment]
If this PR was mergable, why didn't you merge it @samuelet ?

**Comment by samuelet** [comment]
@Klap-in 
Maybe i'm wrong, but in general translation coming from translate.dokuwiki.org makes me feel more secure about their content (@insspb nothing against but don't know Russian, and many other languages :-), so i can't evaluate if a translation is better than another).
Moreover, translate.dokuwiki.org periodically sends PR to indexmenu repo and i'd prefer to think they have the better translation when it will override the existing one.

@insspb 
I did not know that translating Russian with http://translate.dokuwiki.org/ could be few accurate .
As said before, i think that in general and whenever possibile it's a better to contribute to indexemenu translations through transalte.dokuwiki.org but i absolutely don't want to waste any work done by users to improve this plugin so i'm going to merge your pull ;-)

**Comment by samuelet** [comment]
... as soon as someone resove the conflicts ....

**Comment by Klap-in** [comment]
some general notes about the translation tool:
The content is not checked by anybody when the translation tool creates a pull request.
The tools performs only some simple automatic tests which results in some warnings for the translator in the interface. Nothing afterward.

It is just a tool to create a pull request, without troubles for the translator.
When people create manually a pull request, only some of these basic tests are not performed. But the advance is that you are sure it a human that submits. And I assume that people that create manually a pull request, has mosttimes also an installation running where they will test there translation...

(detail: via the tool I have seen already some spam submits, lucky not by people doing manually pull requests.)

**Comment by samuelet** [comment]
This means i was wrong about the translate.dokuwiki.org feeling. I'll keep it in mind in future.

**Comment by Klap-in** [comment]
I manually merge this pull request. I don't know if I made the best choices, because I have selected the lines quite randomly... comments/improvements welcome.

**Comment by insspb** [comment]
Looks right, thx.

**Pull request merged**
