### PR TITLE
nsort sorts namespaces and pages together

### PR DESCRIPTION
**Pull request by rolfik**
When nsort sorting option is switched on, namespaces and pages on the same index level are sorted together.
I use it with msort option as well.
Original behaviour sorted namespaces first and then sorted pages were added.
Maybe new sorting option can be added for this mode.

### CODE REVIEW

**Comment by e-dschungel** [comment]
Is there any chance that this PR gets merged in the official master?

**Comment by rgleason** [comment]
This would sure be a nice improvement for those working with "book" formats.

**Comment by Klap-in** [comment]
I still need to test this, for some different situations.

If others have time for testing, please be welcome to do and report what you test and whether the results were like your expectations.

**Comment by AndreKR** [comment]
FWIW, I applied this to my installation and it works like a charm, thank you!

What I did:
* Change to `lib/plugins/indexmenu`
* Download this MR as a patch using wget by appending `.patch` to this URL:
  `wget https://github.com/samuelet/indexmenu/pull/111.patch`
* Apply it with `patch -p1 < 111.patch`

**Comment by rfertig** [comment]
Which version is your installation?

**Comment by g-wenzel** [comment]
> FWIW, I applied this to my installation and it works like a charm, thank you!
> 
> What I did:
> 
>     * Change to `lib/plugins/indexmenu`
> 
>     * Download this MR as a patch using wget by appending `.patch` to this URL:
>       `wget https://github.com/samuelet/indexmenu/pull/111.patch`
> 
>     * Apply it with `patch -p1 < 111.patch`

Thanks for the advice. I would like to add, that the options nsort AND tsort have to be switched on for this to work (tested with the current release 'Hogfather').

**Comment by Klap-in** [comment]
@eduardomozart Thanks for your pull request! due to conflicts I have apply it manually.

**Comment by Klap-in** [comment]
@rolfik Thanks for contributing this long time ago and your patience! I have implemented it manually due to conflicts with the changes by @eduardomozart due to conflicts.

**Pull request closed without merging**
